# Generated by Django 4.2.5 on 2023-11-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization_registration', '0006_alter_buyer_email_alter_buyer_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
